version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network
    ports:
      - 443:443
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - docker-network

  ftp:
    build: ./requirements/bonus/ftp
    restart: unless-stopped
    volumes:
      - wordpress:/home/rftp_user/ftp/files
    env_file:
      - .env
    networks:
      - docker-network
    ports:
      - 20:20
      - 21:21
      - 990:990
      - 47400-47470:47400-47470

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/rburgsta/data/wordpress
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/rburgsta/data/mariadb
      o: bind

networks:
  docker-network:
    driver: bridge
